# MIT License
# Copyright(c) 2022 Futurewei Cloud
#     Permission is hereby granted,
#     free of charge, to any person obtaining a copy of this software and associated documentation files(the "Software"), to deal in the Software without restriction,
#     including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
#     to whom the Software is furnished to do so, subject to the following conditions:
#     The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
- https://github.com/futurewei-cloud/alcor.git/kubernetes
- https://github.com/networkop/meshnet-cni.git/manifests/base
resources:
- temporal.test.yaml
images:
# Alcor DB Images
- name: ignite_alcor:lib8
  newName: futureweinetworking/ignite_alcor
  newTag: "rio"

# Alcor Service Images
- name: network_config_manager:v1.0
  newName: futureweinetworking/network_config_manager
  newTag: "dev"

- name: api_gateway:v1.0
  newName: futureweinetworking/api_gateway
  newTag: "dev"

- name: data_plane_manager:v1.0
  newName: futureweinetworking/data_plane_manager
  newTag: "dev"

- name: elastic_ip_manager:v1.0
  newName: futureweinetworking/elastic_ip_manager
  newTag: "dev"

- name: gateway_manager:v1.0
  newName: futureweinetworking/gateway_manager
  newTag: "dev"

- name: mac_manager:v1.0
  newName: futureweinetworking/mac_manager
  newTag: "dev"

- name: node_manager:v1.0
  newName: futureweinetworking/node_manager
  newTag: "dev"

- name: port_manager:v1.0
  newName: futureweinetworking/port_manager
  newTag: "dev"

- name: private_ip_manager:v1.0
  newName: futureweinetworking/private_ip_manager
  newTag: "dev"

- name: quota_manager:v1.0
  newName: futureweinetworking/quota_manager
  newTag: "dev"

- name: route_manager:v1.0
  newName: futureweinetworking/route_manager
  newTag: "dev"

- name: security_group_manager:v1.0
  newName: futureweinetworking/security_group_manager
  newTag: "dev"

- name: subnet_manager:v1.0
  newName: futureweinetworking/subnet_manager
  newTag: "dev"

- name: vpc_manager:v1.0
  newName: futureweinetworking/vpc_manager
  newTag: "dev"

replicas:
# Alcor Service
- name: apimanager
  count: 1
- name: dataplanemanager
  count: 1
- name: eipmanager
  count: 1
- name: gatewaymanager
  count: 1
- name: macmanager
  count: 1
- name: netwconfigmanager
  count: 1
- name: nodemanager
  count: 1
- name: ipmanager
  count: 1
- name: portmanager
  count: 1
- name: quotamanager
  count: 1
- name: routemanager
  count: 1
- name: sgmanager
  count: 1
- name: subnetmanager
  count: 1
- name: vpcmanager
  count: 1
# Alcor DB
- name: ignite-alcor-dpm
  count: 1
- name: ignite-alcor-ip
  count: 1
- name: ignite-alcor-mac
  count: 1
- name: ignite-alcor-ncm
  count: 1
- name: ignite-alcor-port
  count: 1
- name: ignite-alcor
  count: 1

configMapGenerator:
- name: api-configmap
  namespace: default
  behavior: replace
  files:
    - alcor/api-gateway/application.properties


